In [1]:
import numpy as np
import pandas as pd
import math

1 : 6 classes  
2 : 12 classes - HF  
3 : 12 classes - IO  
4 : HF vs IO  
5 : 72 exemplars

P1 <-> Partic 9  
P2 <-> Partic 2  
P3 <-> Partic 1  
P4 <-> Partic 4  
P5 <-> Partic 3

## 6 CLASSES

In [2]:
# participant 1
p1_fa_1 = 37.995/100

p1_tmp_str_1 = "Final Accuracy of time window 0-4 is: 15.583%\
Final Accuracy of time window 3-7 is: 18.245%\
Final Accuracy of time window 6-10 is: 27.002%\
Final Accuracy of time window 9-13 is: 36.260%\
Final Accuracy of time window 12-16 is: 34.967%\
Final Accuracy of time window 15-19 is: 31.186%\
Final Accuracy of time window 18-22 is: 25.825%\
Final Accuracy of time window 21-25 is: 23.376%\
Final Accuracy of time window 24-28 is: 19.905%"

p1_tmp_1 = np.zeros(9)

p1_tmp_str_1.split("%")[:-1]

for i in range(len(p1_tmp_str_1.split("%")[:-1])):
    p1_tmp_1[i] = float(p1_tmp_str_1.split("%")[:-1][i].split(":")[1])
    
p1_tmp_1

array([15.583, 18.245, 27.002, 36.26 , 34.967, 31.186, 25.825, 23.376,
       19.905])

In [3]:
# participant 2
p2_fa_1 = 35.816/100

p2_tmp_str_1 = "Final Accuracy of time window 0-4 is: 17.184%\
Final Accuracy of time window 3-7 is: 17.936%\
Final Accuracy of time window 6-10 is: 27.387%\
Final Accuracy of time window 9-13 is: 31.456%\
Final Accuracy of time window 12-16 is: 29.508%\
Final Accuracy of time window 15-19 is: 30.396%\
Final Accuracy of time window 18-22 is: 26.480%\
Final Accuracy of time window 21-25 is: 22.180%\
Final Accuracy of time window 24-28 is: 23.105%"

p2_tmp_1 = np.zeros(9)

p2_tmp_str_1.split("%")[:-1]

for i in range(len(p2_tmp_str_1.split("%")[:-1])):
    p2_tmp_1[i] = float(p2_tmp_str_1.split("%")[:-1][i].split(":")[1])
    
p2_tmp_1

array([17.184, 17.936, 27.387, 31.456, 29.508, 30.396, 26.48 , 22.18 ,
       23.105])

In [4]:
# participant 3
p3_fa_1 = 38.821/100

p3_tmp_str_1 = "Final Accuracy of time window 0-4 is: 15.690%\
Final Accuracy of time window 3-7 is: 19.083%\
Final Accuracy of time window 6-10 is: 27.660%\
Final Accuracy of time window 9-13 is: 35.139%\
Final Accuracy of time window 12-16 is: 35.640%\
Final Accuracy of time window 15-19 is: 32.921%\
Final Accuracy of time window 18-22 is: 29.432%\
Final Accuracy of time window 21-25 is: 26.021%\
Final Accuracy of time window 24-28 is: 26.157%"

p3_tmp_1 = np.zeros(9)

p3_tmp_str_1.split("%")[:-1]

for i in range(len(p3_tmp_str_1.split("%")[:-1])):
    p3_tmp_1[i] = float(p3_tmp_str_1.split("%")[:-1][i].split(":")[1])
    
p3_tmp_1

array([15.69 , 19.083, 27.66 , 35.139, 35.64 , 32.921, 29.432, 26.021,
       26.157])

In [5]:
# participant 4
p4_fa_1 = 35.229/100

p4_tmp_str_1 = "Final Accuracy of time window 0-4 is: 16.834%\
Final Accuracy of time window 3-7 is: 18.666%\
Final Accuracy of time window 6-10 is: 28.442%\
Final Accuracy of time window 9-13 is: 35.134%\
Final Accuracy of time window 12-16 is: 34.285%\
Final Accuracy of time window 15-19 is: 32.625%\
Final Accuracy of time window 18-22 is: 27.998%\
Final Accuracy of time window 21-25 is: 23.043%\
Final Accuracy of time window 24-28 is: 21.307%"

p4_tmp_1 = np.zeros(9)

p4_tmp_str_1.split("%")[:-1]

for i in range(len(p4_tmp_str_1.split("%")[:-1])):
    p4_tmp_1[i] = float(p4_tmp_str_1.split("%")[:-1][i].split(":")[1])
    
p4_tmp_1

array([16.834, 18.666, 28.442, 35.134, 34.285, 32.625, 27.998, 23.043,
       21.307])

In [6]:
# participant 5
p5_fa_1 = 39.452/100

p5_tmp_str_1 = "Final Accuracy of time window 0-4 is: 16.776%\
Final Accuracy of time window 3-7 is: 18.762%\
Final Accuracy of time window 6-10 is: 29.696%\
Final Accuracy of time window 9-13 is: 35.866%\
Final Accuracy of time window 12-16 is: 35.982%\
Final Accuracy of time window 15-19 is: 34.574%\
Final Accuracy of time window 18-22 is: 31.565%\
Final Accuracy of time window 21-25 is: 28.576%\
Final Accuracy of time window 24-28 is: 30.524%"

p5_tmp_1 = np.zeros(9)

p5_tmp_str_1.split("%")[:-1]

for i in range(len(p5_tmp_str_1.split("%")[:-1])):
    p5_tmp_1[i] = float(p5_tmp_str_1.split("%")[:-1][i].split(":")[1])
    
p5_tmp_1

array([16.776, 18.762, 29.696, 35.866, 35.982, 34.574, 31.565, 28.576,
       30.524])

## 12 CLASSES - HF

In [7]:
# participant 1
p1_fa_2 = 12.037/100

p1_tmp_str_2 = "Final Accuracy of time window 0-4 is:7.398%\
Final Accuracy of time window 3-7 is: 9.253%\
Final Accuracy of time window 6-10 is: 9.381%\
Final Accuracy of time window 9-13 is: 12.858%\
Final Accuracy of time window 12-16 is: 11.815%\
Final Accuracy of time window 15-19 is: 10.067%\
Final Accuracy of time window 18-22 is: 9.721%\
Final Accuracy of time window 21-25 is: 9.719%\
Final Accuracy of time window 24-28 is: 10.767%"

p1_tmp_2 = np.zeros(9)

p1_tmp_str_2.split("%")[:-1]

for i in range(len(p1_tmp_str_2.split("%")[:-1])):
    p1_tmp_2[i] = float(p1_tmp_str_2.split("%")[:-1][i].split(":")[1])
    
p1_tmp_2

array([ 7.398,  9.253,  9.381, 12.858, 11.815, 10.067,  9.721,  9.719,
       10.767])

In [8]:
# participant 2
p2_fa_2 = 13.998/100

p2_tmp_str_2 = "Final Accuracy of time window 0-4 is: 8.570%\
Final Accuracy of time window 3-7 is: 6.713%\
Final Accuracy of time window 6-10 is: 13.206%\
Final Accuracy of time window 9-13 is: 18.049%\
Final Accuracy of time window 12-16 is: 13.430%\
Final Accuracy of time window 15-19 is: 12.264%\
Final Accuracy of time window 18-22 is: 12.273%\
Final Accuracy of time window 21-25 is: 9.841%\
Final Accuracy of time window 24-28 is: 11.455%"

p2_tmp_2 = np.zeros(9)

p2_tmp_str_2.split("%")[:-1]

for i in range(len(p2_tmp_str_2.split("%")[:-1])):
    p2_tmp_2[i] = float(p2_tmp_str_2.split("%")[:-1][i].split(":")[1])
    
p2_tmp_2

array([ 8.57 ,  6.713, 13.206, 18.049, 13.43 , 12.264, 12.273,  9.841,
       11.455])

In [9]:
# participant 3
p3_fa_2 = 17.485/100

p3_tmp_str_2 = "Final Accuracy of time window 0-4 is: 11.569%\
Final Accuracy of time window 3-7 is: 8.790%\
Final Accuracy of time window 6-10 is: 14.245%\
Final Accuracy of time window 9-13 is: 17.248%\
Final Accuracy of time window 12-16 is: 15.499%\
Final Accuracy of time window 15-19 is: 15.275%\
Final Accuracy of time window 18-22 is: 13.305%\
Final Accuracy of time window 21-25 is: 14.125%\
Final Accuracy of time window 24-28 is: 12.503%"

p3_tmp_2 = np.zeros(9)

p3_tmp_str_2.split("%")[:-1]

for i in range(len(p3_tmp_str_2.split("%")[:-1])):
    p3_tmp_2[i] = float(p3_tmp_str_2.split("%")[:-1][i].split(":")[1])
    
p3_tmp_2

array([11.569,  8.79 , 14.245, 17.248, 15.499, 15.275, 13.305, 14.125,
       12.503])

In [10]:
# participant 4
p4_fa_2 = 14.012/100

p4_tmp_str_2 = "Final Accuracy of time window 0-4 is: 6.820%\
Final Accuracy of time window 3-7 is: 9.383%\
Final Accuracy of time window 6-10 is: 10.878%\
Final Accuracy of time window 9-13 is: 14.353%\
Final Accuracy of time window 12-16 is: 15.754%\
Final Accuracy of time window 15-19 is: 11.561%\
Final Accuracy of time window 18-22 is: 10.774%\
Final Accuracy of time window 21-25 is: 9.735%\
Final Accuracy of time window 24-28 is: 10.061%"

p4_tmp_2 = np.zeros(9)

p4_tmp_str_2.split("%")[:-1]

for i in range(len(p4_tmp_str_2.split("%")[:-1])):
    p4_tmp_2[i] = float(p4_tmp_str_2.split("%")[:-1][i].split(":")[1])
    
p4_tmp_2

array([ 6.82 ,  9.383, 10.878, 14.353, 15.754, 11.561, 10.774,  9.735,
       10.061])

In [11]:
# participant 5
p5_fa_2 = 16.423/100

p5_tmp_str_2 = "Final Accuracy of time window 0-4 is: 8.561%\
Final Accuracy of time window 3-7 is: 9.477%\
Final Accuracy of time window 6-10 is: 10.740%\
Final Accuracy of time window 9-13 is: 16.188%\
Final Accuracy of time window 12-16 is: 17.233%\
Final Accuracy of time window 15-19 is: 14.574%\
Final Accuracy of time window 18-22 is: 14.912%\
Final Accuracy of time window 21-25 is: 13.291%\
Final Accuracy of time window 24-28 is: 9.829%"

p5_tmp_2 = np.zeros(9)

p5_tmp_str_2.split("%")[:-1]

for i in range(len(p5_tmp_str_2.split("%")[:-1])):
    p5_tmp_2[i] = float(p5_tmp_str_2.split("%")[:-1][i].split(":")[1])
    
p5_tmp_2

array([ 8.561,  9.477, 10.74 , 16.188, 17.233, 14.574, 14.912, 13.291,
        9.829])

## 12 CLASSES - IO


In [12]:
# participant 1
p1_fa_3 = 26/100

p1_tmp_str_3 = "Final Accuracy of time window 0-4 is: 9.268%\
Final Accuracy of time window 3-7 is: 11.001%\
Final Accuracy of time window 6-10 is: 15.273%\
Final Accuracy of time window 9-13 is: 17.597%\
Final Accuracy of time window 12-16 is: 15.500%\
Final Accuracy of time window 15-19 is: 16.080%\
Final Accuracy of time window 18-22 is: 13.070%\
Final Accuracy of time window 21-25 is: 12.037%\
Final Accuracy of time window 24-28 is: 10.640%"

p1_tmp_3 = np.zeros(9)

p1_tmp_str_3.split("%")[:-1]

for i in range(len(p1_tmp_str_3.split("%")[:-1])):
    p1_tmp_3[i] = float(p1_tmp_str_3.split("%")[:-1][i].split(":")[1])
    
p1_tmp_3

array([ 9.268, 11.001, 15.273, 17.597, 15.5  , 16.08 , 13.07 , 12.037,
       10.64 ])

In [13]:
# participant 2
p2_fa_3 = 26.840/100

p2_tmp_str_3 = "Final Accuracy of time window 0-4 is: 8.115%\
Final Accuracy of time window 3-7 is: 9.141%\
Final Accuracy of time window 6-10 is: 15.744%\
Final Accuracy of time window 9-13 is: 19.092%\
Final Accuracy of time window 12-16 is: 18.276%\
Final Accuracy of time window 15-19 is: 20.487%\
Final Accuracy of time window 18-22 is: 14.227%\
Final Accuracy of time window 21-25 is: 11.918%\
Final Accuracy of time window 24-28 is: 12.261%"

p2_tmp_3 = np.zeros(9)

p2_tmp_str_3.split("%")[:-1]

for i in range(len(p2_tmp_str_3.split("%")[:-1])):
    p2_tmp_3[i] = float(p2_tmp_str_3.split("%")[:-1][i].split(":")[1])
    
p2_tmp_3

array([ 8.115,  9.141, 15.744, 19.092, 18.276, 20.487, 14.227, 11.918,
       12.261])

In [14]:
# participant 3
p3_fa_3 = 35.992/100

p3_tmp_str_3 = "Final Accuracy of time window 0-4 is: 7.874%\
Final Accuracy of time window 3-7 is: 9.484%\
Final Accuracy of time window 6-10 is: 20.493%\
Final Accuracy of time window 9-13 is: 24.187%\
Final Accuracy of time window 12-16 is: 30.104%\
Final Accuracy of time window 15-19 is: 31.486%\
Final Accuracy of time window 18-22 is: 22.580%\
Final Accuracy of time window 21-25 is: 21.069%\
Final Accuracy of time window 24-28 is: 15.045%"

p3_tmp_3 = np.zeros(9)

p3_tmp_str_3.split("%")[:-1]

for i in range(len(p3_tmp_str_3.split("%")[:-1])):
    p3_tmp_3[i] = float(p3_tmp_str_3.split("%")[:-1][i].split(":")[1])
    
p3_tmp_3

array([ 7.874,  9.484, 20.493, 24.187, 30.104, 31.486, 22.58 , 21.069,
       15.045])

In [15]:
# participant 4
p4_fa_3 = 18.173/100

p4_tmp_str_3 = "Final Accuracy of time window 0-4 is: 8.103%\
Final Accuracy of time window 3-7 is: 8.681%\
Final Accuracy of time window 6-10 is: 12.955%\
Final Accuracy of time window 9-13 is: 11.799%\
Final Accuracy of time window 12-16 is: 16.545%\
Final Accuracy of time window 15-19 is: 15.275%\
Final Accuracy of time window 18-22 is: 15.739%\
Final Accuracy of time window 21-25 is: 11.466%\
Final Accuracy of time window 24-28 is: 11.925%"

p4_tmp_3 = np.zeros(9)

p4_tmp_str_3.split("%")[:-1]

for i in range(len(p4_tmp_str_3.split("%")[:-1])):
    p4_tmp_3[i] = float(p4_tmp_str_3.split("%")[:-1][i].split(":")[1])
    
p4_tmp_3

array([ 8.103,  8.681, 12.955, 11.799, 16.545, 15.275, 15.739, 11.466,
       11.925])

In [16]:
# participant 5
p5_fa_3 = 29.052/100

p5_tmp_str_3 = "Final Accuracy of time window 0-4 is: 8.341%\
Final Accuracy of time window 3-7 is: 10.303%\
Final Accuracy of time window 6-10 is: 18.867%\
Final Accuracy of time window 9-13 is: 27.080%\
Final Accuracy of time window 12-16 is: 27.430%\
Final Accuracy of time window 15-19 is: 27.521%\
Final Accuracy of time window 18-22 is: 17.711%\
Final Accuracy of time window 21-25 is: 14.006%\
Final Accuracy of time window 24-28 is: 13.095%"

p5_tmp_3 = np.zeros(9)

p5_tmp_str_3.split("%")[:-1]

for i in range(len(p5_tmp_str_3.split("%")[:-1])):
    p5_tmp_3[i] = float(p5_tmp_str_3.split("%")[:-1][i].split(":")[1])
    
p5_tmp_3

array([ 8.341, 10.303, 18.867, 27.08 , 27.43 , 27.521, 17.711, 14.006,
       13.095])

## 2 CLASSES - HF vs IO 

In [17]:
# participant 1
p1_fa_4 = 78.531/100

p1_tmp_str_4 = "Final Accuracy of time window 0-4 is: 49.071%\
Final Accuracy of time window 3-7 is: 55.902%\
Final Accuracy of time window 6-10 is: 70.716%\
Final Accuracy of time window 9-13 is: 78.356%\
Final Accuracy of time window 12-16 is: 74.477%\
Final Accuracy of time window 15-19 is: 70.543%\
Final Accuracy of time window 18-22 is: 60.586%\
Final Accuracy of time window 21-25 is: 58.792%\
Final Accuracy of time window 24-28 is: 56.830%"

p1_tmp_4 = np.zeros(9)

p1_tmp_str_4.split("%")[:-1]

for i in range(len(p1_tmp_str_4.split("%")[:-1])):
    p1_tmp_4[i] = float(p1_tmp_str_4.split("%")[:-1][i].split(":")[1])
    
p1_tmp_4

array([49.071, 55.902, 70.716, 78.356, 74.477, 70.543, 60.586, 58.792,
       56.83 ])

In [18]:
# participant 2
p2_fa_4 =  82.407/100

p2_tmp_str_4 = "Final Accuracy of time window 0-4 is: 52.082%\
Final Accuracy of time window 3-7 is: 55.963%\
Final Accuracy of time window 6-10 is: 71.354%\
Final Accuracy of time window 9-13 is: 76.210%\
Final Accuracy of time window 12-16 is: 70.486%\
Final Accuracy of time window 15-19 is: 73.905%\
Final Accuracy of time window 18-22 is: 69.963%\
Final Accuracy of time window 21-25 is: 61.690%\
Final Accuracy of time window 24-28 is: 63.889%"

p2_tmp_4 = np.zeros(9)

p2_tmp_str_4.split("%")[:-1]

for i in range(len(p2_tmp_str_4.split("%")[:-1])):
    p2_tmp_4[i] = float(p2_tmp_str_4.split("%")[:-1][i].split(":")[1])
    
p2_tmp_4

array([52.082, 55.963, 71.354, 76.21 , 70.486, 73.905, 69.963, 61.69 ,
       63.889])

In [19]:
# participant 3
p3_fa_4 = 79.162/100

p3_tmp_str_4 = "Final Accuracy of time window 0-4 is: 52.550%\
Final Accuracy of time window 3-7 is: 51.619%\
Final Accuracy of time window 6-10 is: 68.054%\
Final Accuracy of time window 9-13 is: 76.328%\
Final Accuracy of time window 12-16 is: 72.629%\
Final Accuracy of time window 15-19 is: 68.752%\
Final Accuracy of time window 18-22 is: 67.072%\
Final Accuracy of time window 21-25 is: 64.350%\
Final Accuracy of time window 24-28 is: 68.113%"

p3_tmp_4 = np.zeros(9)

p3_tmp_str_4.split("%")[:-1]

for i in range(len(p3_tmp_str_4.split("%")[:-1])):
    p3_tmp_4[i] = float(p3_tmp_str_4.split("%")[:-1][i].split(":")[1])
    
p3_tmp_4

array([52.55 , 51.619, 68.054, 76.328, 72.629, 68.752, 67.072, 64.35 ,
       68.113])

In [20]:
# participant 4
p4_fa_4 =  80.435/100

p4_tmp_str_4 = "Final Accuracy of time window 0-4 is: 48.787%\
Final Accuracy of time window 3-7 is: 52.491%\
Final Accuracy of time window 6-10 is: 73.322%\
Final Accuracy of time window 9-13 is: 78.237%\
Final Accuracy of time window 12-16 is: 78.588%\
Final Accuracy of time window 15-19 is: 75.637%\
Final Accuracy of time window 18-22 is: 70.545%\
Final Accuracy of time window 21-25 is: 59.892%\
Final Accuracy of time window 24-28 is: 62.215%"

p4_tmp_4 = np.zeros(9)

p4_tmp_str_4.split("%")[:-1]

for i in range(len(p4_tmp_str_4.split("%")[:-1])):
    p4_tmp_4[i] = float(p4_tmp_str_4.split("%")[:-1][i].split(":")[1])
    
p4_tmp_4

array([48.787, 52.491, 73.322, 78.237, 78.588, 75.637, 70.545, 59.892,
       62.215])

In [21]:
# participant 5
p5_fa_4 =  82.012/100

p5_tmp_str_4 = "Final Accuracy of time window 0-4 is: 51.413%\
Final Accuracy of time window 3-7 is: 56.392%\
Final Accuracy of time window 6-10 is: 70.791%\
Final Accuracy of time window 9-13 is: 76.574%\
Final Accuracy of time window 12-16 is: 78.311%\
Final Accuracy of time window 15-19 is: 71.082%\
Final Accuracy of time window 18-22 is: 68.655%\
Final Accuracy of time window 21-25 is: 73.565%\
Final Accuracy of time window 24-28 is: 71.256%"

p5_tmp_4 = np.zeros(9)

p5_tmp_str_4.split("%")[:-1]

for i in range(len(p5_tmp_str_4.split("%")[:-1])):
    p5_tmp_4[i] = float(p5_tmp_str_4.split("%")[:-1][i].split(":")[1])
    
p5_tmp_4

array([51.413, 56.392, 70.791, 76.574, 78.311, 71.082, 68.655, 73.565,
       71.256])

## 72 CLASSES - EXEMPLARS

In [22]:
# participant 1
p1_fa_5 = 6.847/100

p1_tmp_str_5 = "Final Accuracy of time window 0-4 is: 1.504%\
Final Accuracy of time window 3-7 is: 1.832%\
Final Accuracy of time window 6-10 is: 3.587%\
Final Accuracy of time window 9-13 is: 5.516%\
Final Accuracy of time window 12-16 is: 4.842%\
Final Accuracy of time window 15-19 is: 3.876%\
Final Accuracy of time window 18-22 is: 3.337%\
Final Accuracy of time window 21-25 is: 2.353%\
Final Accuracy of time window 24-28 is: 2.449%"

p1_tmp_5 = np.zeros(9)

p1_tmp_str_5.split("%")[:-1]

for i in range(len(p1_tmp_str_5.split("%")[:-1])):
    p1_tmp_5[i] = float(p1_tmp_str_5.split("%")[:-1][i].split(":")[1])
    
p1_tmp_5

array([1.504, 1.832, 3.587, 5.516, 4.842, 3.876, 3.337, 2.353, 2.449])

In [23]:
# participant 2
p2_fa_5 = 6.365/100

p2_tmp_str_5 = "Final Accuracy of time window 0-4 is: 1.427%\
Final Accuracy of time window 3-7 is: 1.620%\
Final Accuracy of time window 6-10 is: 3.876%\
Final Accuracy of time window 9-13 is: 5.361%\
Final Accuracy of time window 12-16 is: 4.320%\
Final Accuracy of time window 15-19 is: 4.706%\
Final Accuracy of time window 18-22 is: 3.587%\
Final Accuracy of time window 21-25 is: 2.970%\
Final Accuracy of time window 24-28 is: 2.797%"

p2_tmp_5 = np.zeros(9)

p2_tmp_str_5.split("%")[:-1]

for i in range(len(p2_tmp_str_5.split("%")[:-1])):
    p2_tmp_5[i] = float(p2_tmp_str_5.split("%")[:-1][i].split(":")[1])
    
p2_tmp_5

array([1.427, 1.62 , 3.876, 5.361, 4.32 , 4.706, 3.587, 2.97 , 2.797])

In [24]:
# participant 3
p3_fa_5 = 14.321/100

p3_tmp_str_5 = "Final Accuracy of time window 0-4 is: 1.195%\
Final Accuracy of time window 3-7 is: 2.101%\
Final Accuracy of time window 6-10 is: 5.011%\
Final Accuracy of time window 9-13 is: 10.120%\
Final Accuracy of time window 12-16 is: 9.754%\
Final Accuracy of time window 15-19 is: 9.368%\
Final Accuracy of time window 18-22 is: 7.267%\
Final Accuracy of time window 21-25 is: 5.089%\
Final Accuracy of time window 24-28 is: 3.971%"

p3_tmp_5 = np.zeros(9)

p3_tmp_str_5.split("%")[:-1]

for i in range(len(p3_tmp_str_5.split("%")[:-1])):
    p3_tmp_5[i] = float(p3_tmp_str_5.split("%")[:-1][i].split(":")[1])
    
p3_tmp_5

array([ 1.195,  2.101,  5.011, 10.12 ,  9.754,  9.368,  7.267,  5.089,
        3.971])

In [25]:
# participant 4
p4_fa_5 = 5.129/100

p4_tmp_str_5 = "Final Accuracy of time window 0-4 is: 1.273%\
Final Accuracy of time window 3-7 is: 1.581%\
Final Accuracy of time window 6-10 is: 3.239%\
Final Accuracy of time window 9-13 is: 5.534%\
Final Accuracy of time window 12-16 is: 4.609%\
Final Accuracy of time window 15-19 is: 4.223%\
Final Accuracy of time window 18-22 is: 2.661%\
Final Accuracy of time window 21-25 is: 2.102%\
Final Accuracy of time window 24-28 is: 2.121%"

p4_tmp_5 = np.zeros(9)

p4_tmp_str_5.split("%")[:-1]

for i in range(len(p4_tmp_str_5.split("%")[:-1])):
    p4_tmp_5[i] = float(p4_tmp_str_5.split("%")[:-1][i].split(":")[1])
    
p4_tmp_5

array([1.273, 1.581, 3.239, 5.534, 4.609, 4.223, 2.661, 2.102, 2.121])

In [26]:
# participant 5
p5_fa_5 = 10.046/100

p5_tmp_str_5 = "Final Accuracy of time window 0-4 is: 1.408%\
Final Accuracy of time window 3-7 is: 1.620%\
Final Accuracy of time window 6-10 is: 4.377%\
Final Accuracy of time window 9-13 is: 8.330%\
Final Accuracy of time window 12-16 is: 9.622%\
Final Accuracy of time window 15-19 is: 8.060%\
Final Accuracy of time window 18-22 is: 5.842%\
Final Accuracy of time window 21-25 is: 4.647%\
Final Accuracy of time window 24-28 is: 3.664%"

p5_tmp_5 = np.zeros(9)

p5_tmp_str_5.split("%")[:-1]

for i in range(len(p5_tmp_str_5.split("%")[:-1])):
    p5_tmp_5[i] = float(p5_tmp_str_5.split("%")[:-1][i].split(":")[1])
    
p5_tmp_5

array([1.408, 1.62 , 4.377, 8.33 , 9.622, 8.06 , 5.842, 4.647, 3.664])

In [27]:
# append in a list the final accuracies for 6-class classification (1)
accuracies_1 = []
accuracies_1.append(p1_fa_1)
accuracies_1.append(p2_fa_1)
accuracies_1.append(p3_fa_1)
accuracies_1.append(p4_fa_1)
accuracies_1.append(p5_fa_1)

In [28]:
# append in a list the final accuracies for 12c-HF classification (2)
accuracies_2 = []
accuracies_2.append(p1_fa_2)
accuracies_2.append(p2_fa_2)
accuracies_2.append(p3_fa_2)
accuracies_2.append(p4_fa_2)
accuracies_2.append(p5_fa_2)

In [29]:
# append in a list the final accuracies for 12c-IO classification (3)
accuracies_3 = []
accuracies_3.append(p1_fa_3)
accuracies_3.append(p2_fa_3)
accuracies_3.append(p3_fa_3)
accuracies_3.append(p4_fa_3)
accuracies_3.append(p5_fa_3)

In [30]:
# append in a list the final accuracies for HF vs IO classification (4)
accuracies_4 = []
accuracies_4.append(p1_fa_4)
accuracies_4.append(p2_fa_4)
accuracies_4.append(p3_fa_4)
accuracies_4.append(p4_fa_4)
accuracies_4.append(p5_fa_4)

In [31]:
# append in a list the final accuracies for exemplar classif (5)
accuracies_5 = []
accuracies_5.append(p1_fa_5)
accuracies_5.append(p2_fa_5)
accuracies_5.append(p3_fa_5)
accuracies_5.append(p4_fa_5)
accuracies_5.append(p5_fa_5)

### TIME WINDOWS - 6 class


In [32]:
tw_acc_1 = []
tw_acc_1.append(p1_tmp_1)
tw_acc_1.append(p2_tmp_1)
tw_acc_1.append(p3_tmp_1)
tw_acc_1.append(p4_tmp_1)
tw_acc_1.append(p5_tmp_1)

### TIME WINDOWS 12C HF

In [33]:
tw_acc_2 = []
tw_acc_2.append(p1_tmp_2)
tw_acc_2.append(p2_tmp_2)
tw_acc_2.append(p3_tmp_2)
tw_acc_2.append(p4_tmp_2)
tw_acc_2.append(p5_tmp_2)

### TIE WINDOWS 12c IO

In [34]:
tw_acc_3 = []
tw_acc_3.append(p1_tmp_3)
tw_acc_3.append(p2_tmp_3)
tw_acc_3.append(p3_tmp_3)
tw_acc_3.append(p4_tmp_3)
tw_acc_3.append(p5_tmp_3)

### TIME WINDOWS HF vs IO


In [35]:
tw_acc_4 = []
tw_acc_4.append(p1_tmp_4)
tw_acc_4.append(p2_tmp_4)
tw_acc_4.append(p3_tmp_4)
tw_acc_4.append(p4_tmp_4)
tw_acc_4.append(p5_tmp_4)

### TIME WINDOWS 72 EXEMPLARS

In [36]:
tw_acc_5 = []
tw_acc_5.append(p1_tmp_5)
tw_acc_5.append(p2_tmp_5)
tw_acc_5.append(p3_tmp_5)
tw_acc_5.append(p4_tmp_5)
tw_acc_5.append(p5_tmp_5)

### Standard deviations of final accuracies - 5 participants

In [37]:
# 6 classes
std_final_accuracies_1 =  np.std(accuracies_1)
    
# 12 cl - HF
std_final_accuracies_2 =  np.std(accuracies_2)

# 12 cl - IO
std_final_accuracies_3 =  np.std(accuracies_3)

# 2 cl HF - IO
std_final_accuracies_4 =  np.std(accuracies_4)

# 72 cl - exemplars
std_final_accuracies_5 =  np.std(accuracies_5)

std_final_accuracies_all = [std_final_accuracies_1, std_final_accuracies_2, std_final_accuracies_3,
                           std_final_accuracies_4, std_final_accuracies_5]

std_final_accuracies_all = [round(100*x, 4) for x in std_final_accuracies_all]
std_final_accuracies_all

[1.6605, 1.936, 5.7234, 1.5227, 3.3142]

### Mean of final accuracies - 5 participants

In [38]:
# 6 classes
mean_final_accuracies_1 =  np.mean(accuracies_1)
    
# 12 cl - HF
mean_final_accuracies_2 =  np.mean(accuracies_2)


# 12 cl - IO
mean_final_accuracies_3 =  np.mean(accuracies_3)

# 2 cl HF - IO
mean_final_accuracies_4 =  np.mean(accuracies_4)


# 72 cl - exemplars
mean_final_accuracies_5 =  np.mean(accuracies_5)

mean_final_accuracies_all = [mean_final_accuracies_1, mean_final_accuracies_2, mean_final_accuracies_3,
                            mean_final_accuracies_4, mean_final_accuracies_5]

mean_final_accuracies_all = [round(x, 4) for x in mean_final_accuracies_all]
mean_final_accuracies_all

[0.3746, 0.1479, 0.2721, 0.8051, 0.0854]

In [39]:
a = ["6 classes", "12 classes - HF", "12 classes - IO", "2 classes - HF vs IO", "72 classes - Exemplars"]


### Mean of time windows of 5 participants

In [40]:
# 6 classes
tw_all_part_1 = np.array([list(p1_tmp_1), list(p2_tmp_1), list(p3_tmp_1), list(p4_tmp_1), list(p5_tmp_1)])
mean_tw_all_part_1 = tw_all_part_1.mean(axis = 0)
mean_tw_all_part_1 = [round(x, 4) for x in mean_tw_all_part_1]


# 12 classes - HF
tw_all_part_2 = np.array([list(p1_tmp_2), list(p2_tmp_2), list(p3_tmp_2), list(p4_tmp_2), list(p5_tmp_2)])
mean_tw_all_part_2 = tw_all_part_2.mean(axis = 0)
mean_tw_all_part_2 = [round(x, 4) for x in mean_tw_all_part_2]


# 12 classes - IO
tw_all_part_3 = np.array([list(p1_tmp_3), list(p2_tmp_3), list(p3_tmp_3), list(p4_tmp_3), list(p5_tmp_3)])
mean_tw_all_part_3 = tw_all_part_3.mean(axis = 0)
mean_tw_all_part_3 = [round(x, 4) for x in mean_tw_all_part_3]


# 2 classes - HF vs IO
tw_all_part_4 = np.array([list(p1_tmp_4), list(p2_tmp_4), list(p3_tmp_4), list(p4_tmp_4), list(p5_tmp_4)])
mean_tw_all_part_4 = tw_all_part_4.mean(axis = 0)
mean_tw_all_part_4 = [round(x, 4) for x in mean_tw_all_part_4]


# 72 classes - exemplars
tw_all_part_5 = np.array([list(p1_tmp_5), list(p2_tmp_5), list(p3_tmp_5), list(p4_tmp_5), list(p5_tmp_5)])
mean_tw_all_part_5 = tw_all_part_5.mean(axis = 0)
mean_tw_all_part_5 = [round(x, 4) for x in mean_tw_all_part_5]



mean_tw_all_part_all_lvl = [mean_tw_all_part_1, mean_tw_all_part_2, mean_tw_all_part_3,
                           mean_tw_all_part_4, mean_tw_all_part_5]

print(a)
mean_tw_all_part_all_lvl

['6 classes', '12 classes - HF', '12 classes - IO', '2 classes - HF vs IO', '72 classes - Exemplars']


[[16.4134,
  18.5384,
  28.0374,
  34.771,
  34.0764,
  32.3404,
  28.26,
  24.6392,
  24.1996],
 [8.5836, 8.7232, 11.69, 15.7392, 14.7462, 12.7482, 12.197, 11.3422, 10.923],
 [8.3402, 9.722, 16.6664, 19.951, 21.571, 22.1698, 16.6654, 14.0992, 12.5932],
 [50.7806,
  54.4734,
  70.8474,
  77.141,
  74.8982,
  71.9838,
  67.3642,
  63.6578,
  64.4606],
 [1.3614, 1.7508, 4.018, 6.9722, 6.6294, 6.0466, 4.5388, 3.4322, 3.0004]]

### Standard deviation of time windows of 5 participants

In [41]:
# 6 classes
std_1 = tw_all_part_1.std(axis=0)
std_1 = [round(x,4) for x in std_1]

# 12 classes - HF
std_2 = tw_all_part_2.std(axis=0)
std_2 = [round(x,4) for x in std_2]

# 12 classes - IO
std_3 = tw_all_part_3.std(axis=0)
std_3 = [round(x,4) for x in std_3]

# 2 classes - HF vs IO
std_4 = tw_all_part_4.std(axis=0)
std_4 = [round(x,4) for x in std_4]

# 72 classes - exemplars
std_5 = tw_all_part_5.std(axis=0)
std_5 = [round(x,4) for x in std_5]

#print(a, '\n')

std_tw_all_part_all_lvl = [std_1, std_2, std_3, std_4, std_5]
std_tw_all_part_all_lvl = np.array(std_tw_all_part_all_lvl)

if True:
    for j in range(len(a)):
        print(a[j], '\n')
        for i in range(9):
            print('time window', i,'-', i+4, ':', std_tw_all_part_all_lvl[j][i])
            
#std_tw_all_part_all_lvl

6 classes 

time window 0 - 4 : 0.6504
time window 1 - 5 : 0.4029
time window 2 - 6 : 0.9542
time window 3 - 7 : 1.713
time window 4 - 8 : 2.3572
time window 5 - 9 : 1.4505
time window 6 - 10 : 2.0719
time window 7 - 11 : 2.3494
time window 8 - 12 : 3.7905
12 classes - HF 

time window 0 - 4 : 1.6389
time window 1 - 5 : 1.0324
time window 2 - 6 : 1.7731
time window 3 - 7 : 1.8993
time window 4 - 8 : 1.9021
time window 5 - 9 : 1.9262
time window 6 - 10 : 1.8309
time window 7 - 11 : 1.95
time window 8 - 12 : 0.974
12 classes - IO 

time window 0 - 4 : 0.4869
time window 1 - 5 : 0.8308
time window 2 - 6 : 2.6852
time window 3 - 7 : 5.3198
time window 4 - 8 : 6.0019
time window 5 - 9 : 6.37
time window 6 - 10 : 3.3409
time window 7 - 11 : 3.5925
time window 8 - 12 : 1.4584
2 classes - HF vs IO 

time window 0 - 4 : 1.557
time window 1 - 5 : 2.0009
time window 2 - 6 : 1.6855
time window 3 - 7 : 0.9515
time window 4 - 8 : 3.164
time window 5 - 9 : 2.4646
time window 6 - 10 : 3.5935
time wind

In [42]:
mean_accuracies_tw = [mean_tw_all_part_1, mean_tw_all_part_2, mean_tw_all_part_3, mean_tw_all_part_4,
                     mean_tw_all_part_5]

if True:
    for i in range(len(a)):
        print('mean accuracy of', a[i])
        for j in range(len(mean_accuracies_tw)):
            print('time window', j,'-', j+4, ':', mean_accuracies_tw[i][j])
        print('\n')
        
        

mean accuracy of 6 classes
time window 0 - 4 : 16.4134
time window 1 - 5 : 18.5384
time window 2 - 6 : 28.0374
time window 3 - 7 : 34.771
time window 4 - 8 : 34.0764


mean accuracy of 12 classes - HF
time window 0 - 4 : 8.5836
time window 1 - 5 : 8.7232
time window 2 - 6 : 11.69
time window 3 - 7 : 15.7392
time window 4 - 8 : 14.7462


mean accuracy of 12 classes - IO
time window 0 - 4 : 8.3402
time window 1 - 5 : 9.722
time window 2 - 6 : 16.6664
time window 3 - 7 : 19.951
time window 4 - 8 : 21.571


mean accuracy of 2 classes - HF vs IO
time window 0 - 4 : 50.7806
time window 1 - 5 : 54.4734
time window 2 - 6 : 70.8474
time window 3 - 7 : 77.141
time window 4 - 8 : 74.8982


mean accuracy of 72 classes - Exemplars
time window 0 - 4 : 1.3614
time window 1 - 5 : 1.7508
time window 2 - 6 : 4.018
time window 3 - 7 : 6.9722
time window 4 - 8 : 6.6294




In [43]:
# final accuracies mean of 5 participants in whole time-window

final_accuracies_mean = [np.array([p1_fa_1, p2_fa_1, p3_fa_1, p4_fa_1, p5_fa_1]).mean(),
                    np.array([p1_fa_2, p2_fa_2, p3_fa_2, p4_fa_2, p5_fa_2]).mean(),
                    np.array([p1_fa_3, p2_fa_3, p3_fa_3, p4_fa_3, p5_fa_3]).mean(),
                    np.array([p1_fa_4, p2_fa_4, p3_fa_4, p4_fa_4, p5_fa_4]).mean(),
                    np.array([p1_fa_5, p2_fa_5, p3_fa_5, p4_fa_5, p5_fa_5]).mean()]

final_accuracies_mean = [round(100*x, 3) for x in final_accuracies_mean]
#final_accuracies_mean = [str(round(x, 3)) + "%" for x in final_accuracies_mean]
final_accuracies_mean

[37.463, 14.791, 27.211, 80.509, 8.542]

In [44]:
# final accuracies std of 5 participants in whole time-window
print("6 classes, 12 classes HF, 12 classes IO, HF vs IO, 72 exemplars")
final_accuracies_std = [np.array([p1_fa_1, p2_fa_1, p3_fa_1, p4_fa_1, p5_fa_1]).std(),
                    np.array([p1_fa_2, p2_fa_2, p3_fa_2, p4_fa_2, p5_fa_2]).std(),
                    np.array([p1_fa_3, p2_fa_3, p3_fa_3, p4_fa_3, p5_fa_3]).std(),
                    np.array([p1_fa_4, p2_fa_4, p3_fa_4, p4_fa_4, p5_fa_4]).std(),
                    np.array([p1_fa_5, p2_fa_5, p3_fa_5, p4_fa_5, p5_fa_5]).std()]

final_accuracies_std = [round(100*x, 3) for x in final_accuracies_std]
#final_accuracies_std = [str(round(x, 3)) + "%" for x in final_accuracies_std]
final_accuracies_std

6 classes, 12 classes HF, 12 classes IO, HF vs IO, 72 exemplars


[1.661, 1.936, 5.723, 1.523, 3.314]

In [45]:
std_tw_all_part = [std_1, std_2, std_3, std_4, std_5]

In [46]:
mean_accuracies_tw = [mean_tw_all_part_1, mean_tw_all_part_2, mean_tw_all_part_3, mean_tw_all_part_4,
                     mean_tw_all_part_5]
for i in range(len(mean_accuracies_tw)):
    mean_accuracies_tw[i] = [round(x,4) for x in mean_accuracies_tw[i]]
    
j=0
for i in mean_accuracies_tw:
    print(a[j])
    print(i, '\n')
    j+=1
    

6 classes
[16.4134, 18.5384, 28.0374, 34.771, 34.0764, 32.3404, 28.26, 24.6392, 24.1996] 

12 classes - HF
[8.5836, 8.7232, 11.69, 15.7392, 14.7462, 12.7482, 12.197, 11.3422, 10.923] 

12 classes - IO
[8.3402, 9.722, 16.6664, 19.951, 21.571, 22.1698, 16.6654, 14.0992, 12.5932] 

2 classes - HF vs IO
[50.7806, 54.4734, 70.8474, 77.141, 74.8982, 71.9838, 67.3642, 63.6578, 64.4606] 

72 classes - Exemplars
[1.3614, 1.7508, 4.018, 6.9722, 6.6294, 6.0466, 4.5388, 3.4322, 3.0004] 



In [47]:
tw_accuracies_means = np.array([mean_tw_all_part_1, mean_tw_all_part_2,
                      mean_tw_all_part_3, mean_tw_all_part_4, mean_tw_all_part_5])


print(tw_accuracies_means)

[[16.4134 18.5384 28.0374 34.771  34.0764 32.3404 28.26   24.6392 24.1996]
 [ 8.5836  8.7232 11.69   15.7392 14.7462 12.7482 12.197  11.3422 10.923 ]
 [ 8.3402  9.722  16.6664 19.951  21.571  22.1698 16.6654 14.0992 12.5932]
 [50.7806 54.4734 70.8474 77.141  74.8982 71.9838 67.3642 63.6578 64.4606]
 [ 1.3614  1.7508  4.018   6.9722  6.6294  6.0466  4.5388  3.4322  3.0004]]


In [48]:
tw_accuracies_stds = np.array([std_1, std_2, std_3, std_4, std_5])


print(tw_accuracies_stds)

[[0.6504 0.4029 0.9542 1.713  2.3572 1.4505 2.0719 2.3494 3.7905]
 [1.6389 1.0324 1.7731 1.8993 1.9021 1.9262 1.8309 1.95   0.974 ]
 [0.4869 0.8308 2.6852 5.3198 6.0019 6.37   3.3409 3.5925 1.4584]
 [1.557  2.0009 1.6855 0.9515 3.164  2.4646 3.5935 5.2983 4.9621]
 [0.1116 0.1961 0.6209 1.9255 2.5032 2.2325 1.7331 1.214  0.7073]]


In [49]:
# for all levels of classifications, mean of participants, list of length 6
final_accuracies_mean  

# for all levels of classifications, std of all participants, list of length 6
final_accuracies_std  

# for all levels of classifications, mean of each tw for all prtcp, array.shape = (5,9)
tw_accuracies_means = np.array([np.round(x,2) for x in tw_accuracies_means])
tw_accuracies_means

# for all levels of classifications, mean of each tw for all prtcp, array.shape = (5,9)
#std_tw_all_part_all_lvl 

array([[16.41, 18.54, 28.04, 34.77, 34.08, 32.34, 28.26, 24.64, 24.2 ],
       [ 8.58,  8.72, 11.69, 15.74, 14.75, 12.75, 12.2 , 11.34, 10.92],
       [ 8.34,  9.72, 16.67, 19.95, 21.57, 22.17, 16.67, 14.1 , 12.59],
       [50.78, 54.47, 70.85, 77.14, 74.9 , 71.98, 67.36, 63.66, 64.46],
       [ 1.36,  1.75,  4.02,  6.97,  6.63,  6.05,  4.54,  3.43,  3.  ]])

In [50]:
# create 3 dataframes of size 5-levels x 1-statistic x 10-tw  =  15 x 10

colnames = ['0-496ms', 'tw 0-4', 'tw 3-7', 'tw 6-10', 'tw 9-13', 'tw 12-16', 
              'tw 15-19', 'tw 18-22', 'tw 21-25', 'tw 24-28']

rownames = a 

# ACCURACIES DF

df_acc = pd.DataFrame(0, index=a, columns=colnames)


df_acc["0-496ms"] = final_accuracies_mean
df_acc

for i in range(tw_accuracies_means.shape[0]):
    df_acc.iloc[i,1:] = tw_accuracies_means[i]
df_acc

0-496ms  tw 0-4  tw 3-7  tw 6-10  tw 9-13  tw 12-16  \
6 classes                37.463   16.41   18.54    28.04    34.77     34.08   
12 classes - HF          14.791    8.58    8.72    11.69    15.74     14.75   
12 classes - IO          27.211    8.34    9.72    16.67    19.95     21.57   
2 classes - HF vs IO     80.509   50.78   54.47    70.85    77.14     74.90   
72 classes - Exemplars    8.542    1.36    1.75     4.02     6.97      6.63   

                        tw 15-19  tw 18-22  tw 21-25  tw 24-28  
6 classes                  32.34     28.26     24.64     24.20  
12 classes - HF            12.75     12.20     11.34     10.92  
12 classes - IO            22.17     16.67     14.10     12.59  
2 classes - HF vs IO       71.98     67.36     63.66     64.46  
72 classes - Exemplars      6.05      4.54      3.43      3.00

In [51]:
colnames = ['0-496ms', 'tw 0-4', 'tw 3-7', 'tw 6-10', 'tw 9-13', 'tw 12-16', 
              'tw 15-19', 'tw 18-22', 'tw 21-25', 'tw 24-28']

rownames = a 

# STD DF

df_std = pd.DataFrame(0, index=a, columns=colnames)


df_std["0-496ms"] = final_accuracies_std
df_std

for i in range(tw_accuracies_stds.shape[0]):
    df_std.iloc[i,1:] = tw_accuracies_stds[i]
df_std

0-496ms  tw 0-4  tw 3-7  tw 6-10  tw 9-13  tw 12-16  \
6 classes                 1.661  0.6504  0.4029   0.9542   1.7130    2.3572   
12 classes - HF           1.936  1.6389  1.0324   1.7731   1.8993    1.9021   
12 classes - IO           5.723  0.4869  0.8308   2.6852   5.3198    6.0019   
2 classes - HF vs IO      1.523  1.5570  2.0009   1.6855   0.9515    3.1640   
72 classes - Exemplars    3.314  0.1116  0.1961   0.6209   1.9255    2.5032   

                        tw 15-19  tw 18-22  tw 21-25  tw 24-28  
6 classes                 1.4505    2.0719    2.3494    3.7905  
12 classes - HF           1.9262    1.8309    1.9500    0.9740  
12 classes - IO           6.3700    3.3409    3.5925    1.4584  
2 classes - HF vs IO      2.4646    3.5935    5.2983    4.9621  
72 classes - Exemplars    2.2325    1.7331    1.2140    0.7073

In [80]:
import scipy
from scipy import stats

colnames = ['0-496ms', 'tw 0-4', 'tw 3-7', 'tw 6-10', 'tw 9-13', 'tw 12-16', 
              'tw 15-19', 'tw 18-22', 'tw 21-25', 'tw 24-28']

rownames = a 

N = 5184/10
p_priors = [1/6, 1/12, 1/12, 1/2, 1/72]

# STD DF

df_pval = pd.DataFrame(float(0), index=a, columns=colnames)

for i in range(5):
    x = math.floor(N*final_accuracies_mean[i]/100)
    pr = p_priors[i]
    #if scipy.stats.binom_test(x, N, pr) < 10**(-14):
     #   df_pval["0-496ms"][i] = 1
    #else:
    tmp = "{:e}".format(scipy.stats.binom_test(x, N, pr))
    tmp = np.format_float_scientific(float(tmp), precision=3)
    df_pval["0-496ms"][i] = tmp

for i in range(5):
    for j in range(9):
        x = math.floor(N*tw_accuracies_means[i,j]/100)
        pr = p_priors[i]
        tmp = "{:e}".format(scipy.stats.binom_test(x,N,pr, alternative = 'greater'))
        tmp = np.format_float_scientific(float(tmp), precision=3)
        df_pval.iloc[i,1+ j] = tmp
    
    
    
df_pval

0-496ms     tw 0-4     tw 3-7    tw 6-10  \
6 classes               1.102000e-29  5.807e-01  1.403e-01  8.095e-11   
12 classes - HF         2.127000e-06  4.701e-01  4.079e-01  6.416e-03   
12 classes - IO         1.014000e-36  5.335e-01  1.569e-01  8.363e-10   
2 classes - HF vs IO    1.325000e-46  3.792e-01  2.396e-02  4.413e-22   
72 classes - Exemplars  4.542000e-21  5.801e-01  2.958e-01  5.488e-05   

                          tw 9-13   tw 12-16   tw 15-19   tw 18-22   tw 21-25  \
6 classes               1.726e-23  8.314e-22  3.086e-18  4.097e-11  3.337e-06   
12 classes - HF         3.834e-08  1.235e-06  4.179e-04  1.764e-03  1.395e-02   
12 classes - IO         1.618e-16  3.321e-20  1.139e-21  8.363e-10  8.326e-06   
2 classes - HF vs IO    1.211e-36  3.907e-31  1.763e-24  9.683e-16  2.281e-10   
72 classes - Exemplars   7.95e-15   2.19e-13  2.511e-11   1.67e-06  1.167e-03   

                         tw 24-28  
6 classes               8.939e-06  
12 classes - HF         2.834e-02  
12 classes - IO         6.865e-04  
2 classes - HF vs IO    2.168e-11  
72 classes - Exemplars  6.836e-03

In [81]:
colnames = ['0-496ms', 'tw 0-4', 'tw 3-7', 'tw 6-10', 'tw 9-13', 'tw 12-16', 
              'tw 15-19', 'tw 18-22', 'tw 21-25', 'tw 24-28']

arrays = [['6 classes',
 '6 classes',
 '6 classes',
 '12 classes - HF',
 '12 classes - HF',
 '12 classes - HF',
 '12 classes - IO',
 '12 classes - IO',
 '12 classes - IO',
 '2 classes - HF vs IO',
 '2 classes - HF vs IO',
 '2 classes - HF vs IO',
 '72 classes - Exemplars',
 '72 classes - Exemplars',
 '72 classes - Exemplars'],
    ['accuracy %', 'sample std', 'p-value','accuracy %', 'sample std', 'p-value',
    'accuracy %', 'sample std', 'p-value','accuracy %', 'sample std', 'p-value',
    'accuracy %', 'sample std', 'p-value']]

tuples = list(zip(*arrays))
# STD DF

index = pd.MultiIndex.from_tuples(tuples)

df = pd.DataFrame(0, index=index, columns=colnames)
df

j = 0
for i in range(0,15,3):
    df.iloc[i] = df_acc.iloc[j]
    df.iloc[i+1] = df_std.iloc[j]
    df.iloc[i+2] = df_pval.iloc[j]
    j = j+1
df["0-496ms"] = df["0-496ms"].apply(lambda x: '%3f' % x if x>0.00001 else x)
df["0-496ms"] = df["0-496ms"].apply(lambda x: str(x).rstrip("0"))
df

0-496ms     tw 0-4     tw 3-7    tw 6-10  \
6 classes              accuracy %     37.463      16.41      18.54      28.04   
                       sample std      1.661     0.6504     0.4029     0.9542   
                       p-value     1.102e-29  5.807e-01  1.403e-01  8.095e-11   
12 classes - HF        accuracy %     14.791       8.58       8.72      11.69   
                       sample std      1.936     1.6389     1.0324     1.7731   
                       p-value     2.127e-06  4.701e-01  4.079e-01  6.416e-03   
12 classes - IO        accuracy %     27.211       8.34       9.72      16.67   
                       sample std      5.723     0.4869     0.8308     2.6852   
                       p-value     1.014e-36  5.335e-01  1.569e-01  8.363e-10   
2 classes - HF vs IO   accuracy %     80.509      50.78      54.47      70.85   
                       sample std      1.523      1.557     2.0009     1.6855   
                       p-value     1.325e-46  3.792e-01  2.396e-02  4.413e-22   
72 classes - Exemplars accuracy %      8.542       1.36       1.75       4.02   
                       sample std      3.314     0.1116     0.1961     0.6209   
                       p-value     4.542e-21  5.801e-01  2.958e-01  5.488e-05   

                                     tw 9-13   tw 12-16   tw 15-19   tw 18-22  \
6 classes              accuracy %      34.77      34.08      32.34      28.26   
                       sample std      1.713     2.3572     1.4505     2.0719   
                       p-value     1.726e-23  8.314e-22  3.086e-18  4.097e-11   
12 classes - HF        accuracy %      15.74      14.75      12.75       12.2   
                       sample std     1.8993     1.9021     1.9262     1.8309   
                       p-value     3.834e-08  1.235e-06  4.179e-04  1.764e-03   
12 classes - IO        accuracy %      19.95      21.57      22.17      16.67   
                       sample std     5.3198     6.0019       6.37     3.3409   
                       p-value     1.618e-16  3.321e-20  1.139e-21  8.363e-10   
2 classes - HF vs IO   accuracy %      77.14       74.9      71.98      67.36   
                       sample std     0.9515      3.164     2.4646     3.5935   
                       p-value     1.211e-36  3.907e-31  1.763e-24  9.683e-16   
72 classes - Exemplars accuracy %       6.97       6.63       6.05       4.54   
                       sample std     1.9255     2.5032     2.2325     1.7331   
                       p-value      7.95e-15   2.19e-13  2.511e-11   1.67e-06   

                                    tw 21-25   tw 24-28  
6 classes              accuracy %      24.64       24.2  
                       sample std     2.3494     3.7905  
                       p-value     3.337e-06  8.939e-06  
12 classes - HF        accuracy %      11.34      10.92  
                       sample std       1.95      0.974  
                       p-value     1.395e-02  2.834e-02  
12 classes - IO        accuracy %       14.1      12.59  
                       sample std     3.5925     1.4584  
                       p-value     8.326e-06  6.865e-04  
2 classes - HF vs IO   accuracy %      63.66      64.46  
                       sample std     5.2983     4.9621  
                       p-value     2.281e-10  2.168e-11  
72 classes - Exemplars accuracy %       3.43          3  
                       sample std      1.214     0.7073  
                       p-value     1.167e-03  6.836e-03